#!/usr/bin/env bash
set -euo pipefail
trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#set -o xtrace

function cat_csv {
  local csv_files_file_name="$1"
  local clean_up=no

  if [[ -z "$csv_files_file_name" ]]
  then
    csv_files_file_name=$(mktemp)
    cat > "$csv_files_file_name"
    clean_up=yes
  fi 

  # Copy the first CSV file, including its header row.
  cat $(head --lines=1 "$csv_files_file_name")

  # Copy the remaining CSV files, absent their header rows. 
  tail --lines=+2 "$csv_files_file_name" | xargs tail --lines=+2 --silent

  if [[ $clean_up == "yes" ]]
  then
    rm -f $csv_files_file_name
  fi
}

csv_files_file_name=${1:-}
cat_csv "$csv_files_file_name"
