#!/usr/bin/env bash
set -euo pipefail
trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#set -o xtrace

function cat_csv {
  local csv_files_file_name="$1"

  # Copy the first CSV file, including its header row.
  cat $(head --lines=1 "$csv_files_file_name")

  # Copy the remaining CSV files, absent their header rows.
  # Ignore pipefail error. See https://stackoverflow.com/q/22464786/107158.
  tail --lines=+2 "$csv_files_file_name" |
    xargs tail --lines=+2 --silent 2>/dev/null \
    || [[ $? -eq 125 ]] && true || exit $?
}

if (( $# > 1 ))
then
  csv_files_file_name=$(mktemp)
  trap "rm -f $csv_files_file_name" EXIT
  echo "$@" | tr ' ' '\n' > $csv_files_file_name
elif (( $# == 1))
then
  csv_files_file_name=${1:-}
else
  csv_files_file_name=$(mktemp)
  trap "rm -f $csv_files_file_name" EXIT
  cat > "$csv_files_file_name"
fi

cat_csv "$csv_files_file_name"
