#!/usr/bin/env bash
set -euo pipefail
trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#set -o xtrace

top_directory_name=$(mktemp --tmpdir=. --directory)
trap "rm -fr $top_directory_name" EXIT

working_directory_name=$(mktemp --tmpdir=$top_directory_name --directory)

temp_file_names=$(
  parallel \
    --files \
    --keep-order \
    --xargs \
    --tmpdir $working_directory_name \
    ./cat_csv
)

temp_file_names_count=$(echo "$temp_file_names" | wc -l)

while [[ $temp_file_names_count -gt 1 ]]
do
  old_working_directory_name=$working_directory_name
  working_directory_name=$(mktemp --tmpdir=$top_directory_name --directory)
  temp_file_names=$(echo "$temp_file_names" |
    parallel \
      --files \
      --keep-order \
      --tempdir $working_directory_name \
      --xargs \
      ./cat_csv
  )
  temp_file_names_count=$(echo "$temp_file_names" | wc -l)
  rm -fr $old_working_directory_name
done

cat $temp_file_names || [[ $? -eq 141 ]] && true || exit $?
